# Generated by Django 5.0.4 on 2024-05-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=200)),
                ('dashboard_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.dashboards'),
        ),
        migrations.CreateModel(
            name='Users_Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dashboards')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users')),
            ],
        ),
    ]
