# Generated by Django 5.0.6 on 2024-05-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dashboards_dashboard_admin_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboards',
            name='users',
            field=models.ManyToManyField(related_name='dashboards', through='base.Users_Dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='dashboard_admin_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='admin_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('done', 'Done')], default='Done', max_length=20),
        ),
    ]
